Check and Throw error when ID is Non-existent, when method is update …
onaio/fhir-tooling pull request #135
Opened 2024-02-13 14:03 UTC by TraciebelWairimu

…and Test cases for the same

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #130

**Engineer Checklist**
- [ ] I have run `./gradlew spotlessApply` to check my code follows the project's style guide
- [ ] I have built and run the efsity jar to verify my change fixes the issue and/or does not break the application

2024-02-14 19:29 UTC, pld requested changes

2024-02-14 19:29 UTC, pld commented on importer/main.py
> +        return False
you can simplify this to use a single `return` statement

2024-02-15 17:25 UTC, Wambere commented
Added a DNM until we get the tests working

2024-02-15 21:14 UTC, pld approved these changes
lgtm!

2024-02-16 05:14 UTC, merged