Fix regression bugs in pr 214
onaio/fhir-tooling pull request #228
Opened 2024-07-18 09:36 UTC by hilpitome

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] or Closes #[issue number]

**Engineer Checklist**
- [ ] I have run `./gradlew spotlessApply` to check my code follows the project's style guide
- [ ] I have built and run the efsity jar to verify my change fixes the issue and/or does not break the application

2024-07-18 09:38 UTC, hilpitome commented
This fixes bugs that were introduced by PR #214. Running most of the commands [here](https://github.com/onaio/fhir-tooling/pull/214) resulted in failure.

2024-07-18 11:24 UTC, ndegwamartin commented on efsity/src/main/java/org/smartregister/command/TranslateCommand.java
> +      if (extractionType.equals("configs")) {
Start with the string for the condition here. Usually preferred incase the object is null. i.e. 
```java
"configs".equals(extractionType)
```

2024-07-18 11:30 UTC, ndegwamartin commented on efsity/src/main/java/org/smartregister/command/TranslateCommand.java
>            if (Objects.equals(extractionType, "configs") || inputFilePath.endsWith("configs")) {
You can switch this as well since one of them is a string in the comparison

2024-07-18 11:31 UTC, ndegwamartin commented on efsity/src/main/java/org/smartregister/command/TranslateCommand.java
> +            if (Objects.equals(extractionType, null)) extractionType = "configs";
This is okay since one is null. This approach is preferred when both are objects

2024-07-18 11:33 UTC, ndegwamartin commented
Is it possible to capture the regression in a test case so that we can avoid future cases on the same? 

If high LOE you can create a ticket to track this and get this merged in for the Hotfix else you can add it to this PR.

2024-07-18 13:42 UTC, hilpitome commented
I can add the test in this PR

2024-10-23 13:29 UTC, pld requested changes
@hilpitome please add a test

2025-01-16 00:58 UTC, pld approved these changes

2025-01-16 00:58 UTC, pld commented
@hilpitome can you please generate (and adjust if needed) a test and include that in a new PR

2025-01-16 01:00 UTC, merged